// Code generated by protoc-gen-go. DO NOT EDIT.
// source: car.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CarWithoutIdPb struct {
	Brand                string               `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model                string               `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CarWithoutIdPb) Reset()         { *m = CarWithoutIdPb{} }
func (m *CarWithoutIdPb) String() string { return proto.CompactTextString(m) }
func (*CarWithoutIdPb) ProtoMessage()    {}
func (*CarWithoutIdPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{0}
}

func (m *CarWithoutIdPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarWithoutIdPb.Unmarshal(m, b)
}
func (m *CarWithoutIdPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarWithoutIdPb.Marshal(b, m, deterministic)
}
func (m *CarWithoutIdPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarWithoutIdPb.Merge(m, src)
}
func (m *CarWithoutIdPb) XXX_Size() int {
	return xxx_messageInfo_CarWithoutIdPb.Size(m)
}
func (m *CarWithoutIdPb) XXX_DiscardUnknown() {
	xxx_messageInfo_CarWithoutIdPb.DiscardUnknown(m)
}

var xxx_messageInfo_CarWithoutIdPb proto.InternalMessageInfo

func (m *CarWithoutIdPb) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *CarWithoutIdPb) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *CarWithoutIdPb) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type GetCarRequestPb struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCarRequestPb) Reset()         { *m = GetCarRequestPb{} }
func (m *GetCarRequestPb) String() string { return proto.CompactTextString(m) }
func (*GetCarRequestPb) ProtoMessage()    {}
func (*GetCarRequestPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{1}
}

func (m *GetCarRequestPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCarRequestPb.Unmarshal(m, b)
}
func (m *GetCarRequestPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCarRequestPb.Marshal(b, m, deterministic)
}
func (m *GetCarRequestPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCarRequestPb.Merge(m, src)
}
func (m *GetCarRequestPb) XXX_Size() int {
	return xxx_messageInfo_GetCarRequestPb.Size(m)
}
func (m *GetCarRequestPb) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCarRequestPb.DiscardUnknown(m)
}

var xxx_messageInfo_GetCarRequestPb proto.InternalMessageInfo

func (m *GetCarRequestPb) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCarRequestPb struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCarRequestPb) Reset()         { *m = DeleteCarRequestPb{} }
func (m *DeleteCarRequestPb) String() string { return proto.CompactTextString(m) }
func (*DeleteCarRequestPb) ProtoMessage()    {}
func (*DeleteCarRequestPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{2}
}

func (m *DeleteCarRequestPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCarRequestPb.Unmarshal(m, b)
}
func (m *DeleteCarRequestPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCarRequestPb.Marshal(b, m, deterministic)
}
func (m *DeleteCarRequestPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCarRequestPb.Merge(m, src)
}
func (m *DeleteCarRequestPb) XXX_Size() int {
	return xxx_messageInfo_DeleteCarRequestPb.Size(m)
}
func (m *DeleteCarRequestPb) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCarRequestPb.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCarRequestPb proto.InternalMessageInfo

func (m *DeleteCarRequestPb) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CarPb struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand                string               `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model                string               `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CarPb) Reset()         { *m = CarPb{} }
func (m *CarPb) String() string { return proto.CompactTextString(m) }
func (*CarPb) ProtoMessage()    {}
func (*CarPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b9800c53a1ba42, []int{3}
}

func (m *CarPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarPb.Unmarshal(m, b)
}
func (m *CarPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarPb.Marshal(b, m, deterministic)
}
func (m *CarPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarPb.Merge(m, src)
}
func (m *CarPb) XXX_Size() int {
	return xxx_messageInfo_CarPb.Size(m)
}
func (m *CarPb) XXX_DiscardUnknown() {
	xxx_messageInfo_CarPb.DiscardUnknown(m)
}

var xxx_messageInfo_CarPb proto.InternalMessageInfo

func (m *CarPb) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CarPb) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *CarPb) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *CarPb) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func init() {
	proto.RegisterType((*CarWithoutIdPb)(nil), "pb.CarWithoutIdPb")
	proto.RegisterType((*GetCarRequestPb)(nil), "pb.GetCarRequestPb")
	proto.RegisterType((*DeleteCarRequestPb)(nil), "pb.DeleteCarRequestPb")
	proto.RegisterType((*CarPb)(nil), "pb.CarPb")
}

func init() {
	proto.RegisterFile("car.proto", fileDescriptor_f8b9800c53a1ba42)
}

var fileDescriptor_f8b9800c53a1ba42 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0xc4, 0xa6, 0x64, 0x84, 0x0a, 0xab, 0x94, 0x10, 0x0f, 0xd6, 0xe0, 0xa1, 0x08,
	0x6e, 0xa1, 0x0a, 0x9e, 0x3c, 0x45, 0x11, 0x6f, 0x21, 0x0a, 0x9e, 0x77, 0x93, 0xb1, 0x06, 0x12,
	0x37, 0x6e, 0x36, 0x42, 0x7f, 0xad, 0x7f, 0x45, 0xb2, 0x6b, 0xac, 0x34, 0xb6, 0x78, 0x9c, 0x37,
	0x6f, 0xf6, 0xcd, 0x37, 0x0b, 0x5e, 0xca, 0x24, 0xad, 0xa4, 0x50, 0x82, 0xd8, 0x15, 0x0f, 0x4e,
	0x96, 0x42, 0x2c, 0x0b, 0x9c, 0x6b, 0x85, 0x37, 0x2f, 0x73, 0x95, 0x97, 0x58, 0x2b, 0x56, 0x56,
	0xc6, 0x14, 0x1c, 0x6f, 0x1a, 0xb0, 0xac, 0xd4, 0xca, 0x34, 0x43, 0x09, 0xe3, 0x88, 0xc9, 0xe7,
	0x5c, 0xbd, 0x8a, 0x46, 0x3d, 0x64, 0x31, 0x27, 0x47, 0x30, 0xe4, 0x92, 0xbd, 0x65, 0xbe, 0x35,
	0xb5, 0x66, 0x5e, 0x62, 0x8a, 0x56, 0x2d, 0x45, 0x86, 0x85, 0x6f, 0x1b, 0x55, 0x17, 0xe4, 0x0a,
	0x46, 0xa9, 0x44, 0xa6, 0x30, 0xf3, 0x9d, 0xa9, 0x35, 0xdb, 0x5f, 0x04, 0xd4, 0x84, 0xd1, 0x2e,
	0x8c, 0x3e, 0x75, 0xdb, 0x24, 0x9d, 0x35, 0x3c, 0x85, 0x83, 0x7b, 0x54, 0x11, 0x93, 0x09, 0xbe,
	0x37, 0x58, 0xab, 0x98, 0x93, 0x31, 0xd8, 0xb9, 0x49, 0x74, 0x12, 0x3b, 0xcf, 0xc2, 0x33, 0x20,
	0xb7, 0x58, 0xa0, 0xc2, 0x9d, 0xae, 0x15, 0x0c, 0x23, 0x26, 0xfb, 0x8d, 0x35, 0x83, 0xfd, 0x27,
	0x83, 0xb3, 0x85, 0x61, 0xef, 0xdf, 0x0c, 0x8b, 0x4f, 0x0b, 0x20, 0x62, 0xf2, 0x11, 0xe5, 0x47,
	0x9e, 0x22, 0x39, 0x07, 0xd7, 0x20, 0x91, 0x43, 0x5a, 0x71, 0xba, 0x81, 0x17, 0x78, 0xad, 0xa8,
	0x57, 0x0d, 0x07, 0xe4, 0x1a, 0x46, 0xb1, 0xa8, 0xb5, 0x99, 0x7c, 0xeb, 0xbf, 0xee, 0x1f, 0x4c,
	0x7a, 0xf1, 0x77, 0xed, 0x7f, 0x85, 0x03, 0x72, 0x01, 0x6e, 0xdc, 0xe8, 0xb9, 0xf5, 0x7b, 0x3b,
	0xec, 0x37, 0xe0, 0xfd, 0xdc, 0x90, 0x4c, 0xda, 0x89, 0xfe, 0x49, 0xb7, 0x8f, 0x73, 0x57, 0x2b,
	0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0xdc, 0x81, 0x68, 0x6f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CarServiceClient is the client API for CarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarServiceClient interface {
	GetCar(ctx context.Context, in *GetCarRequestPb, opts ...grpc.CallOption) (*CarPb, error)
	PostCar(ctx context.Context, in *CarWithoutIdPb, opts ...grpc.CallOption) (*empty.Empty, error)
	PutCar(ctx context.Context, in *CarPb, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteCar(ctx context.Context, in *DeleteCarRequestPb, opts ...grpc.CallOption) (*empty.Empty, error)
}

type carServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarServiceClient(cc grpc.ClientConnInterface) CarServiceClient {
	return &carServiceClient{cc}
}

func (c *carServiceClient) GetCar(ctx context.Context, in *GetCarRequestPb, opts ...grpc.CallOption) (*CarPb, error) {
	out := new(CarPb)
	err := c.cc.Invoke(ctx, "/pb.CarService/GetCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carServiceClient) PostCar(ctx context.Context, in *CarWithoutIdPb, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.CarService/PostCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carServiceClient) PutCar(ctx context.Context, in *CarPb, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.CarService/PutCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carServiceClient) DeleteCar(ctx context.Context, in *DeleteCarRequestPb, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.CarService/DeleteCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarServiceServer is the server API for CarService service.
type CarServiceServer interface {
	GetCar(context.Context, *GetCarRequestPb) (*CarPb, error)
	PostCar(context.Context, *CarWithoutIdPb) (*empty.Empty, error)
	PutCar(context.Context, *CarPb) (*empty.Empty, error)
	DeleteCar(context.Context, *DeleteCarRequestPb) (*empty.Empty, error)
}

// UnimplementedCarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCarServiceServer struct {
}

func (*UnimplementedCarServiceServer) GetCar(ctx context.Context, req *GetCarRequestPb) (*CarPb, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCar not implemented")
}
func (*UnimplementedCarServiceServer) PostCar(ctx context.Context, req *CarWithoutIdPb) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostCar not implemented")
}
func (*UnimplementedCarServiceServer) PutCar(ctx context.Context, req *CarPb) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutCar not implemented")
}
func (*UnimplementedCarServiceServer) DeleteCar(ctx context.Context, req *DeleteCarRequestPb) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCar not implemented")
}

func RegisterCarServiceServer(s *grpc.Server, srv CarServiceServer) {
	s.RegisterService(&_CarService_serviceDesc, srv)
}

func _CarService_GetCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCarRequestPb)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServer).GetCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CarService/GetCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServer).GetCar(ctx, req.(*GetCarRequestPb))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarService_PostCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarWithoutIdPb)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServer).PostCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CarService/PostCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServer).PostCar(ctx, req.(*CarWithoutIdPb))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarService_PutCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarPb)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServer).PutCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CarService/PutCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServer).PutCar(ctx, req.(*CarPb))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarService_DeleteCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCarRequestPb)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServer).DeleteCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CarService/DeleteCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServer).DeleteCar(ctx, req.(*DeleteCarRequestPb))
	}
	return interceptor(ctx, in, info, handler)
}

var _CarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CarService",
	HandlerType: (*CarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCar",
			Handler:    _CarService_GetCar_Handler,
		},
		{
			MethodName: "PostCar",
			Handler:    _CarService_PostCar_Handler,
		},
		{
			MethodName: "PutCar",
			Handler:    _CarService_PutCar_Handler,
		},
		{
			MethodName: "DeleteCar",
			Handler:    _CarService_DeleteCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car.proto",
}
